//@version=5
indicator(title="My Test for empty string", overlay=true)

// Calculate and plot two Exponential Moving Average
emaFast = ta.ema(close, 9)
emaSlow = ta.ema(close, 21)

plot(emaFast, color=color.orange, title="EMA Fast")
plot(emaSlow, color=color.teal, linewidth=2, title="EMA Slow")

// Calculate the conditions for the arrows
crossUp = ta.cross(emaFast, emaSlow) and emaFast > emaSlow
crossDown = ta.cross(emaFast, emaSlow) and emaFast < emaSlow

// Plot the arrows
plotshape(crossUp, color=color.blue, style=shape.arrowup, location=location.abovebar, text = "B")
plotshape(crossDown, color=color.red, style=shape.arrowdown, location=location.belowbar, text = "S")